cienciadedatos/dados

README.Rmd, README.md
solo una primera traducción del readme
=> first version of README in portuguese

DESCRIPTION
=> typo + Sara

inst/specs/awardmanagers.yml
Olá, segue a primeira tradução dos dados awardmanagers para iniciar revisão. Obrigada.
=> primeira tradução dos dados awardmanagers

inst/specs/common.yml
Olá, segue a primeira tradução dos dados common para revisar. Obrigada.
=> primeira tradução dos dados common

DESCRIPTION, README.Rmd, README.md, data/data.R, inst/scripts/comuns.txt, inst/scripts/dados_gapminder.txt, inst/scripts/premios_gerentes.txt, inst/specs/common.yml, man/comuns.rd, man/dados-package.Rd, man/dados_gapminder.rd, man/premios_gerentes.rd
=> update package with new translations

inst/specs/atmos.yml
Olá! Alguém pode revisar? Obrigada :D
=> Primeira tradução nasaweather::atmos

R/rd.R, docs/pkgdown.yml, docs/reference/comuns.html, docs/reference/dados_atmosfera.html, docs/reference/dados_gapminder.html, docs/reference/diamante.html, docs/reference/premios_gerentes.html, inst/specs/atmos.yml, man/comuns.rd, man/dados_atmosfera.rd, man/dados_gapminder.rd, man/diamante.rd, man/premios_gerentes.rd
=> add See Also to help page

DESCRIPTION
Olá, segue a atualização do nome a description. Obrigada.
=> adiciona nome a description

inst/specs/flights.yml
=> Tradução nycflights13::flights

inst/specs/airlines.yml
=> Traducao nycflights13::airlines

inst/specs/table2.yml
Oi pessoal, segue a primeira tradução da base table2. Alguém pode revisar? Obrigada
=> Tradução tidyr::table2

inst/specs/table1.yml
Olá! Fiz a tradução de uma base mais simples, para testar como funciona.
=> Tradução tidyr::table1

inst/specs/table4a.yml, inst/specs/table4b.yml
Fiz as duas bases em um mesmo PR pois são quase iguais...
=> Traducao tidyr::table4a e tidyr::table4b

inst/specs/presidential.yml
Alguém pode revisar essa base por favor?
Muito agradecida :)
=> Tradução ggplot2::presidential

inst/specs/vehicles.yml
Segunda versão :) se alguém puder revisão por favor
=> Segunda versão da tradução fueleconomy::vehicles

inst/specs/managers.yml
Olá! Segue a primeira tradução dos dados managers para revisão. Obrigada!
=> primeira tradução dos dados managers

README.md, data/data.R, docs/404.html, docs/LICENSE.html, docs/authors.html, docs/index.html, docs/pkgdown.yml, docs/reference/comuns.html, docs/reference/dados-package.html, docs/reference/dados_atmosfera.html, docs/reference/dados_gapminder.html, docs/reference/diamante.html, docs/reference/gerentes.html, docs/reference/index.html, docs/reference/premios_gerentes.html, docs/reference/presidentes_eua.html, docs/reference/tabela1.html, docs/reference/tabela2.html, docs/reference/tabela3.html, docs/reference/tabela4a.html, docs/reference/tabela4b.html, docs/reference/veiculos.html, docs/reference/voos.html, inst/scripts/gerentes.txt, inst/scripts/veiculos.txt, man/gerentes.rd, man/veiculos.rd
Add new translations + Jean's info to package and package website
=> update package + site

README.md, data/data.R, docs/index.html, docs/pkgdown.yml, docs/reference/dados_iris.html, docs/reference/tabela5.html, docs/reference/veiculos.html, docs/reference/velho_fiel.html, inst/scripts/dados_iris.txt, inst/scripts/tabela5.txt, inst/scripts/velho_fiel.txt, inst/specs/faithful.yml, inst/specs/iris.yml, inst/specs/managers.yml, inst/specs/table5.yml, inst/specs/vehicles.yml, man/dados-package.Rd, man/dados_iris.rd, man/tabela5.rd, man/veiculos.rd, man/velho_fiel.rd
=> update package + site with new translations

DESCRIPTION, data/data.R, inst/scripts/ames.txt, inst/specs/ames.yml, man/ames.rd, man/dados-package.Rd
Tradução das variáveis e suas categorias da base AmesHousing::ames_raw com base nas informações encontradas nessa documentação: http://jse.amstat.org/v19n3/decock/DataDocumentation.txt
=> Tradução da base AmesHousing::ames_raw

inst/specs/pitching.yml
=> corrigindo arremessadores

inst/specs/gss-cats.yml
Typo: repubicano instead of republicano.
=> Typo: Update gss-cats.yml
